language: crystal
env:
  global:
  - GH_REF: github.com/icyleaf/gitlab.cr
  - secure: NBIS3videU8FhaNes5Ma8WD+mKl4OdCcBuMWUvEqPCr6L1zBtqA2C4RsCWOJuZTOa2cJYmgIp/nQa60rZNzrMD9O1ugp6CJ2GCRmqlxVXh+/4BqjZuzUpaf90EKO5+TzvQcHQGrFz53pEsn+4H8FQSG8R0GnT4dyjf80v9xRrGLuxhTqyGqfgcQ9uBBodhuYtZ/WIG6+0tyCqwK5ZCoNSZ2EfOGRTEsEVKVolCA7Dfyo91oLNWPvhhxqnUO96yt6TVqs/f72GmgXK7NeKDBKf7fF7vxj13oTp/JXJOx+oayp/bXlwSfZns1pMlTCfMR3MNe45yWYsuU/jCMaoJlrfXui+4Lft+Vxpsk3JH1ZTStZaybSovd3ITfoTtNTQY0tdGJE53GNYyzeMi0i9rq062dDU2be6r0avgrVOof+0AU+PpGOkOEY6e60bJW12I62r2SYyXBYuSwcJpOIOMIyfdKy/y+dqG/9Mu7JtBjny8dLb+pLZ2mbTNfpiYDO8TRunOcPfK7turCxr7PRxDSWfPukFAMGhvK2hNUNhtsAlZFxz6kcj/UoYsd+HMYPPtcQhgEGs/8giF9ol0guBxur1WuW8WeUlrzf/lAM2kIlZncjNnSZXsx/pw+AfnpBofcW0vwUdDHux+9vywj1h4TT70JeYtte6OC947EFuEq1T+4=
script:
- crystal spec
after_script:
- COMMIT_HASH=$(git rev-parse --short HEAD)
- COMMIT_DATE=$(git log -1 --format=%ci)
- COMMIT_STATUS="[${COMMIT_HASH}](https://${GH_REF}/commit/${COMMIT_HASH})"
- sed -i -e "s/latest commit/$(echo ${COMMIT_STATUS} | sed -e "s/\//\\\\\//g") (${COMMIT_DATE})/"
  README.md
- crystal docs
- cd doc
- git config --global user.name "icyleaf"
- git config --global user.email "icyleaf.cn@gmail.com"
- git init
- git remote add origin "https://${GH_TOKEN}@${GH_REF}.git"
- git fetch origin
- git reset origin/gh-pages
- git add -A .
- git commit -m "Updating to ${COMMIT_HASH}"
- git push origin HEAD:gh-pages
