language: crystal
env:
  global:
  - GH_REF: github.com/icyleaf/gitlab.cr
  - secure: XMYLwszWMR7xhlH1AGuHk6TrGcY9pHlqJ9BVLVeRW0OGnh9jr0GbMm2BErDcdLgs5Um/3r4Y5Ve+1GMNTBqOfxztWmph0q6eUAGveSt0bRd7CReCnCmL6kHUlZMrtO3lt9fgIUsXv+1dzNtJLrV4qO2fBWjCKbEMjOfxTXFeLhRaimyxBe2qLwd9On+C/kxOVk3IAHAT/cUFUP6ZoKHLi14XGJf/AjYyU+0JWbfIxA8t6RXlSp24+NwnU1BZ2W4NArrpVRtb3tzizoDveATzw8OS23g4LE0sKd2+MD/vrlTNMWJHjCMa2v5CzfPJ3sm41AOmO2CgSAzDYH4yWSNDrMawtJ0QQEZtzrDVIwrUHlUUxLN6LIa7DIHevVG0jzaG9SWMp/1+zUEarRaGPL1tvvvgpR8TInfU5Y4GBOjA6bKoql+rsBng1hnIlhNfY285UUB5x0UnbCrA/CG6d+pi0h1wvuEe27nQyGi80rTn4q23o6YK5AWJBqCjYbt6rbmv9Ih3WWsaIQcXLGh7qP3Yc6nxFYEZbmmgOfTcQKEEEP/En8qNVVO6QFK7ddNns5aIrY9b33AxFJLaA2F3FYdqpYRDhCRGU7x/YhvNZYu8u2YtrO+fQI/AFAJ9MRW9JiiIfrOjWk+HNwoDLLj/EjlI+ppn57/ST7epa8wSYKWe4jk=
script:
  - crystal docs
after_script:
  - COMMIT_HASH=$(git rev-parse --short HEAD)
  - COMMIT_DATE=$(git log -1 --format=%ci)
  - crystal docs
  - cd doc
  - git config --global user.name "Travis CI"
  - git config --global user.email "robot@travis.org"
  - git init
  - git remote add upstream "https://${GH_TOKEN}@${GH_REF}.git"
  - git fetch upstream
  - git reset upstream/gh-pages
  - sed -i -e "s/latest commit/${COMMIT_HASH}/" README.md
  - git add -A .
  - git commit -m "Updating to ${COMMIT_HASH}"
  - git push --quiet upsteam HEAD:gh-pages